from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('health/', views.health_check, name='health_check'),
    path('status/', views.status_page, name='status_page'),
    path('login/', views.login_view, name='login'),
    path('student-view/auth/', views.student_view_auth, name='student_view_auth'),

    path('teacher-view/auth/', views.teacher_view_auth, name='teacher_view_auth'),


    path('teacher/signup/', views.teacher_signup_view, name='teacher_signup'),
    path('teacher/login/', views.teacher_login_view, name='teacher_login'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/courses/', views.my_courses, name='my_courses'),
    path('teacher/analytics/', views.teacher_analytics_view, name='teacher_analytics'),
    path('teacher/courses/create/', views.create_course, name='create_course'),
    path('teacher/courses/<uuid:course_uid>/edit/', views.edit_course, name='edit_course'),
    path('teacher/courses/<uuid:course_uid>/delete/', views.delete_course, name='delete_course'),
    path('teacher/courses/<uuid:course_uid>/lessons/', views.course_lessons, name='course_lessons'),
    path('teacher/courses/<uuid:course_uid>/lessons/add/', views.add_lesson, name='add_lesson'),
    path('teacher/lessons/<uuid:lesson_uid>/edit/', views.edit_lesson, name='edit_lesson'),
    path('teacher/lessons/<uuid:lesson_uid>/delete/', views.delete_lesson, name='delete_lesson'),
    path('course/<uuid:course_uid>/resource/add/', views.add_resource, name='add_resource'),
    path('resource/<uuid:resource_uid>/edit/', views.edit_resource, name='edit_resource'),
    path('resource/<uuid:resource_uid>/delete/', views.delete_resource, name='delete_resource'),
    path('teacher/courses/<uuid:course_uid>/submit/', views.submit_course_approval, name='submit_course_approval'),
    path('student/enroll/<uuid:course_uid>/', views.enroll_course, name='enroll_course'),
    path('logout/', views.logout_view, name='logout'),
    path('teacher/courses/view/<uuid:course_uid>/', views.view_other_course, name='view_other_course'),
    path('teacher/explore/', views.explore_courses, name='teacher_explore'),
    path('course/<uuid:course_uid>/play/', views.course_player, name='course_player'),
    path('resource/<uuid:resource_uid>/access/', views.access_resource, name='access_resource'),
    path('resource/<uuid:resource_uid>/view/', views.pdf_viewer, name='pdf_viewer'),
    path('resource/<uuid:resource_uid>/download/', views.download_resource, name='download_resource'),
    path('resource/<uuid:resource_uid>/stream/<str:token>/', views.stream_resource, name='stream_resource'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('student/explore/', views.student_explore, name='student_explore'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('teacher/profile/edit/', views.teacher_edit_profile, name='teacher_edit_profile'),
    path('chat/send/', views.send_chat_message, name='send_chat_message'),
    path('chat/messages/<uuid:other_user_uid>/', views.get_chat_messages, name='get_chat_messages'),
    path('chat/list/', views.get_chat_list, name='get_chat_list'),
    path('notification/<uuid:notif_uid>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notification/<uuid:notif_uid>/delete/', views.delete_notification, name='delete_notification'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/', views.all_notifications, name='all_notifications'),
    path('unread-counts/', views.get_unread_counts, name='get_unread_counts'),
    path('check-username/', views.check_username, name='check_username'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('recover-username/', views.recover_username, name='recover_username'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('api/youtube/init-upload/', views.init_youtube_upload, name='init_youtube_upload'),
    path('api/youtube/upload/<uuid:job_uid>/progress/', views.update_upload_progress, name='update_upload_progress'),
    path('api/youtube/upload/<uuid:job_uid>/complete/', views.complete_youtube_upload, name='complete_youtube_upload'),
    path('api/youtube/upload/<uuid:job_uid>/status/', views.get_upload_status, name='get_upload_status'),
    path('api/backup/', views.trigger_backup, name='trigger_backup'),
    path('api/dismiss-updates/', views.dismiss_updates, name='dismiss_updates'),
]



