from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('teacher/signup/', views.teacher_signup_view, name='teacher_signup'),
    path('teacher/login/', views.teacher_login_view, name='teacher_login'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/courses/', views.my_courses, name='my_courses'),
    path('teacher/courses/create/', views.create_course, name='create_course'),
    path('teacher/courses/<int:course_id>/edit/', views.edit_course, name='edit_course'),
    path('teacher/courses/<int:course_id>/lessons/', views.course_lessons, name='course_lessons'),
    path('teacher/courses/<int:course_id>/lessons/add/', views.add_lesson, name='add_lesson'),
    path('teacher/lessons/<int:lesson_id>/edit/', views.edit_lesson, name='edit_lesson'),
    path('teacher/lessons/<int:lesson_id>/delete/', views.delete_lesson, name='delete_lesson'),
    path('teacher/courses/<int:course_id>/submit/', views.submit_course_approval, name='submit_course_approval'),
    path('teacher/courses/<int:course_id>/quiz/create/', views.create_quiz, name='create_quiz'),
    path('teacher/quiz/<int:quiz_id>/questions/add/', views.add_questions, name='add_questions'),
    path('teacher/courses/<int:course_id>/assignment/create/', views.create_assignment, name='create_assignment'),
    path('student/enroll/<int:course_id>/', views.enroll_course, name='enroll_course'),
    path('student/quiz/<int:quiz_id>/take/', views.take_quiz, name='take_quiz'),
    path('student/assignment/<int:assignment_id>/submit/', views.submit_assignment, name='submit_assignment'),
    path('teacher/quiz/<int:quiz_id>/results/', views.view_quiz_results, name='view_quiz_results'),
    path('teacher/assignment/<int:assignment_id>/submissions/', views.view_submissions, name='view_submissions'),
    path('teacher/submission/<int:submission_id>/grade/', views.grade_submission, name='grade_submission'),
    path('logout/', views.logout_view, name='logout'),
    path('teacher/courses/view/<int:course_id>/', views.view_other_course, name='view_other_course'),
    path('teacher/explore/', views.explore_courses, name='teacher_explore'),
    path('course/<int:course_id>/play/', views.course_player, name='course_player'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
]

