# Generated by Django 5.2.7 on 2026-05-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10),
        ),
    ]

