# Generated by Django 5.2.7 on 2026-05-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10),
        ),
    ]
