# Generated by Django 5.2.7 on 2026-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_course_approved_by_course_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]

