# Generated by Django 6.0.4 on 2026-05-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_deletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Supabase PDF URL', max_length=1000, null=True),
        ),
    ]

