# Generated by Django 6.0.4 on 2026-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lesson_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]

