# Generated by Django 6.0.4 on 2026-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_lessonnote_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='proof_file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='proof_pdf',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
