# Generated by Django 5.2.7 on 2026-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_assignment_status_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]

