# Generated by Django 5.2.7 on 2026-05-04 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_course_uid_alter_customuser_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]

