# Generated by Django 5.2.7 on 2026-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_chatmessage_uid_alter_deletionrequest_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='proof_pdf',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
