# Generated by Django 5.2.7 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_course_image_course_image_public_id_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pdf_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected')], db_index=True, default='ACTIVE', max_length=10),
        ),
    ]
