# Generated by Django 5.2.7 on 2026-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_customuser_pdf_path_pdfaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]

