# Generated by Django 5.2.7 on 2026-05-07 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_customuser_totp_secret_adminactivitylog_loginhistory'),
    ]

    operations = [
        migrations.createModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10)),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('USERNAME_RECOVERY', 'Username Recovery'), ('EMAIL_UPDATE', 'Email Update'), ('USERNAME_UPDATE', 'Username Update')], default='PASSWORD_RESET', max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]



