# Generated by Django 5.2.7 on 2026-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_emailotp_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
