# Generated by Django 5.2.7 on 2026-05-29 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_course_has_pending_edits_course_pending_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ENGLISH', 'English Notes'), ('MALAYALAM', 'Malayalam Notes'), ('ONLINE', 'Online Class Notes')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('PPTX', 'PowerPoint Presentation'), ('XLSX', 'Excel Spreadsheet'), ('TXT', 'Text File')], db_index=True, max_length=10)),
                ('firebase_file_path', models.CharField(max_length=1000)),
                ('backup_file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('original_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('compressed_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resources', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='accounts.course')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
