# Generated by Django 5.2.7 on 2026-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_courseresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
