# Generated by Django 5.2.7 on 2026-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_courseresource_thumbnail_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='backup_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10),
        ),
    ]

