# Generated by Django 5.2.7 on 2026-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_deletionrequest_resource_deletionrequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='has_pending_edits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_compressed_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_firebase_file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_original_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_resource_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_thumbnail_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_thumbnail_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
