# Generated by Django 5.2.7 on 2026-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_courseresource_has_pending_edits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_upload_status',
            field=models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], db_index=True, default='NOT_UPLOADED', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID from upload', max_length=100, null=True),
        ),
    ]
