# Generated by Django 5.2.7 on 2026-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_lesson_youtube_upload_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_co_status_e347e4_idx ON accounts_course (status, is_approved, created_at DESC)",
            "DROP INDEX IF EXISTS accounts_co_status_e347e4_idx"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_co_teacher_b8a57d_idx ON accounts_course (teacher_id, status, created_at DESC)",
            "DROP INDEX IF EXISTS accounts_co_teacher_b8a57d_idx"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_cu_user_ty_02b313_idx ON accounts_customuser (user_type, status)",
            "DROP INDEX IF EXISTS accounts_cu_user_ty_02b313_idx"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_de_status_6935ec_idx ON accounts_deletionrequest (status, created_at DESC)",
            "DROP INDEX IF EXISTS accounts_de_status_6935ec_idx"
        ),
    ]
