# Generated by Django 5.2.7 on 2026-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_lesson_youtube_upload_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='accounts_ch_sender__38b152_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='accounts_ch_receive_b9970d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', 'status', 'is_deleted'], name='accounts_co_course__fe0b26_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['status', 'is_deleted'], name='accounts_co_status_cb8a67_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', '-created_at'], name='accounts_co_course__1d2d31_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'status'], name='accounts_cu_user_ty_02b313_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number', 'user_type'], name='accounts_cu_phone_n_419fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'user'], name='accounts_en_course__f6dc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'status'], name='accounts_le_course__649c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_b490c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'status', '-timestamp'], name='accounts_lo_user_id_f51a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', 'user'], name='accounts_lo_ip_addr_b4ed0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx'),
        ),
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
