# Generated by Django 5.2.7 on 2026-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_customuser_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='courseresource',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_approved', '-created_at'], name='accounts_co_status_e347e4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'status', '-created_at'], name='accounts_co_teacher_b8a57d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'status'], name='accounts_cu_user_ty_02b313_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionrequest',
            index=models.Index(fields=['status', '-created_at'], name='accounts_de_status_6935ec_idx'),
        ),
    ]
