# Generated by Django 5.2.7 on 2026-06-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_courseresource_options_courseresource_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['-created_at']},
        ),
    ]
