# Generated by Django 5.2.7 on 2026-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Video file size in bytes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='upload_status',
            field=models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('PENDING', 'Pending Upload'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='NOT_UPLOADED', max_length=20),
        ),
    ]
