# Generated by Django 5.2.7 on 2026-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_add_lesson_upload_status_and_file_size'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_approved', '-created_at'], name='accounts_co_status_e347e4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'status', '-created_at'], name='accounts_co_teacher_b8a57d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status', 'user_type', '-date_joined'], name='accounts_cu_status_8ed248_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionrequest',
            index=models.Index(fields=['status', '-created_at'], name='accounts_de_status_6935ec_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_em_user_id_7388a1_idx'),
        ),
    ]
