# Generated by Django 5.2.7 on 2026-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_course_accounts_co_status_e347e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['chapter', 'order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.CharField(blank=True, help_text='Chapter grouping name (e.g. Chapter 1)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pending_chapter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
