# Generated by Django 5.2.7 on 2026-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_lesson_options_lesson_chapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['chapter', 'order']},
        ),
        migrations.AddField(
            model_name='courseresource',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order within chapter'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='pending_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
