# Generated by Django 5.2.7 on 2026-06-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_course_chapters_courseresource_chapter_and_more'),
        ('accounts', '0050_upload_job_model'),
    ]

    operations = [
    ]
