# Generated by Django 5.2.7 on 2026-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_merge_20260604_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='order',
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text="Admin's feedback/reason when approving or rejecting the request", null=True),
        ),
    ]
