# Generated by Django 5.2.7 on 2026-06-07 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('DATABASE', 'Database Backup'), ('SIGNUP_PDF', 'Signup PDF Backup'), ('TEACHER_RESOURCE', 'Teacher Resource Backup')], db_index=True, max_length=50)),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('drive_folder_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('UPLOADING', 'Uploading'), ('VERIFYING', 'Verifying'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('duration_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('verify_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (course_id, user_id, etc.)')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backup_type', '-created_at'], name='accounts_ba_backup__afa644_idx'), models.Index(fields=['status', '-created_at'], name='accounts_ba_status_934b6d_idx'), models.Index(fields=['backup_type', 'status'], name='accounts_ba_backup__a56d4c_idx')],
            },
        ),
    ]
