# Generated by Django 5.2.7 on 2026-06-07 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_customuser_chat_display_name_customuser_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('message_uid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('supabase_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_EDITED', 'Message Edited'), ('MESSAGE_DELETED', 'Message Deleted'), ('ATTACHMENT_SENT', 'Attachment Sent'), ('CONVERSATION_STATUS', 'Conversation Status Changed'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('CONVERSATION_EXPORTED', 'Conversation Exported')], db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='accounts_ch_action_6c4ed8_idx'), models.Index(fields=['actor', '-timestamp'], name='accounts_ch_actor_i_b695b8_idx')],
            },
        ),
    ]
