# Generated by Django 5.2.7 on 2026-06-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_add_chat_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'PDF Document')], db_index=True, max_length=10),
        ),
    ]
