# Generated by Django 5.2.7 on 2026-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_courseresource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('UPLOADING', 'Uploading'), ('VERIFYING', 'Verifying'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CLEANED', 'Cleaned by retention')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
