# Generated by Django 5.2.7 on 2026-06-12 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_courseresource_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='processing_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='processing_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='chunk_size',
            field=models.PositiveIntegerField(default=5242880, help_text='Chunk size in bytes (default 5MB)'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='file_hash_first_5mb',
            field=models.CharField(blank=True, default='', help_text='SHA256 of first 5MB for resume verification', max_length=64),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='mime_type',
            field=models.CharField(blank=True, default='video/mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='processing_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='processing_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='session_created_at',
            field=models.DateTimeField(blank=True, help_text='When the YouTube resumable session was created', null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the YouTube session is expected to expire', null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded to YouTube'), ('YOUTUBE_PROCESSING', 'YouTube Processing'), ('PROCESSING', 'Processing on YouTube'), ('SUCCEEDED', 'YouTube Processing Succeeded'), ('COMPLETED', 'Completed'), ('READY', 'Ready'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='UploadAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('UPLOAD_STARTED', 'Upload Started'), ('CHUNK_UPLOADED', 'Chunk Uploaded'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('CANCELLED', 'Cancelled'), ('RETRY', 'Retry'), ('SESSION_RENEWED', 'Session Renewed'), ('SESSION_EXPIRED', 'Session Expired'), ('UPLOAD_COMPLETED', 'Upload Completed'), ('PROCESSING', 'Processing'), ('PROCESSING_VERIFIED', 'Processing Verified'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('DELETED', 'Deleted'), ('RESTORED', 'Restored'), ('CLEANUP', 'Cleanup'), ('QUERY_RESUMED', 'Query Resumed'), ('NETWORK_LOST', 'Network Lost'), ('NETWORK_RESTORED', 'Network Restored')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('upload_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='accounts.uploadjob')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['upload_job', '-timestamp'], name='accounts_up_upload__d96977_idx'), models.Index(fields=['event_type', '-timestamp'], name='accounts_up_event_t_9b3826_idx')],
            },
        ),
    ]
