# Generated by Django 5.2.7 on 2026-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_courseresource_status_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('DAILY_FULL', 'Daily Full Backup'), ('DATABASE', 'Database Backup'), ('SIGNUP_PDF', 'Signup PDF Backup'), ('TEACHER_RESOURCE', 'Teacher Resource Backup'), ('LIVE_DB', 'Live DB Restore (Primary → Backup Supabase)')], db_index=True, max_length=50),
        ),
    ]
