# Generated by Django 5.2.7 on 2026-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_backuplog_backup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('DAILY_FULL', 'Daily Full Backup'), ('DATABASE', 'Database Backup'), ('SIGNUP_PDF', 'Signup PDF Backup'), ('TEACHER_RESOURCE', 'Teacher Resource Backup'), ('LIVE_DB', 'Live DB Restore (Primary → Backup Supabase)'), ('DRIVE', 'Google Drive Real-time Backup')], db_index=True, max_length=50),
        ),
    ]
